# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00a9aec25d411c4cf8e9d8c46a0bb5d3b98b0c88e1c1ef81f6dddd1b88539e301b44e48d978f7a42f2ab3c15c0a0b2a150a1a2538d4fb2880dc0480c041fc50

test:
  secret_key_base: 289dd09ff0ccc64f117bf353bc2e9476a2514037aa18bb0c82c523289af8a2e039fb8d7f8bf39e253210fadba58be014c74384b23af7703484aa10b40a8e3f8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
